enable_ssl: True
handle_cookie: True

host:
  self: mirror-google-cn.vercel.app
  proxy: www.startpage.com

replaced_urls:
  - old: www.startpage.com
    new: www.startpage.com
  - old: www.startpage.com
    new: mirror-google-cn.vercel.app
